#Task level variables
- name: variables from prompt level
  hosts: localhost
  vars_prompt: 
  - name: USERNAME
    prompt: Please enter your username
    private: false #user can see what they are enter
  - name: PASSWORD
    prompt: Please enter your password
    private: true #user can't see what they are enter
  tasks:
  - name: print and check the values
    ansible.builtin.debug:
     msg: "username is {{USERNAME}} and password is {{PASSWORD}}"