- name: conditions
  hosts: localhost
  become: yes
  tasks: 
  - name: check roboshop user exists or not
    ansible.builtin.command: id roboshop
    register: user #user is a variable name. It stores id roboshop
    ignore_errors: true #ansible will not exit even it got error

  - name: print variable value
    ansible.builtin.debug:
     msg: "user output is: {{user}}"

  - name: print exit status or return code
    ansible.builtin.debug:
     msg: "user exit status is: {{user.rc}}" 

  - name: create new user with name roboshop
    ansible.builtin.user:
     name: roboshop
    when: user.rc != 0 #condition

  - name: check roboshop user exists or not
    ansible.builtin.command: id roboshop
    register: user #user is a variable name. It stores id roboshop